import AdminAccess from '../admin/AdminAccess';
import { useEffect, useState } from 'react';
import { ArrowRight, Users, Ticket, Wallet, BedDouble, Download, Search, LogOut, CheckCircle2 } from 'lucide-react';
import { Frame } from './RegistrationPages';
import { Button } from '../components/Shared';
import { registrationService as service } from './service';
import { currency, paymentNames } from './catalog';
import { ordersCsv, statusNames, paymentStatusNames } from './demoService';
import { PaymentHistory } from './PaymentPanel';
import '../styles/reservations.css';

const date = value => new Date(value).toLocaleString('pt-BR', { dateStyle: 'short', timeStyle: 'short' });
function DemoOnly() { return <div className="registration-width registration-error"><h1>Área de demonstração desativada</h1><p>A área de contas e reservas precisa da autenticação e dos serviços administrativos da API para operar fora do teste.</p><Button href="/evento">Voltar ao evento</Button></div>; }
function OrderList({ orders }) { return <div className="recent-orders">{orders.length ? orders.map(order => <a className="account-order" href={`/acompanhamento?codigo=${order.id}`} key={order.id}><Ticket size={21}/><span><b>{order.id}</b><small>{order.accommodation} · {order.participantCount} participante(s)</small></span><span>{currency(order.totalCents)}<small>{statusNames[order.status]}</small></span><ArrowRight size={16}/></a>) : <p>Seu primeiro encontro começa aqui. <a href="/inscricao">Fazer uma inscrição</a></p>}</div>; }

export function AccountPage() {
  return <Frame active="account" title="Minha conta">{service.mode === 'demo' ? <AccountContent/> : <DemoOnly/>}</Frame>;
}
function AccountContent() {
  const [account, setAccount] = useState(null), [orders, setOrders] = useState([]), [loading, setLoading] = useState(true);
  const [tab, setTab] = useState('register'), [form, setForm] = useState({ name: '', email: '', code: '', confirm: '' });
  const [error, setError] = useState(''), [busy, setBusy] = useState(false);
  const next = new URLSearchParams(location.search).get('retorno') === 'inscricao' ? '/inscricao' : '/evento';
  useEffect(() => { let active = true; Promise.all([service.currentAccount(), service.recentOrders()]).then(([user, list]) => { if (active) { setAccount(new URLSearchParams(location.search).get('novo') === '1' ? null : user); setOrders(list); } }).catch(err => active && setError(err.message)).finally(() => active && setLoading(false)); return () => { active = false; }; }, []);
  async function submit(e) {
    e.preventDefault(); setError('');
    if (tab === 'register' && form.code !== form.confirm) { setError('Os códigos de teste precisam ser iguais.'); return; }
    setBusy(true);
    try { const user = await service[tab === 'register' ? 'createAccount' : 'login'](form); setAccount(user); setOrders(await service.recentOrders()); setForm({ name: '', email: '', code: '', confirm: '' }); } catch (err) { setError(err.message); } finally { setBusy(false); }
  }
  async function logout() { await service.logout(); setAccount(null); setOrders([]); }
  const field = (key, label, type = 'text', props = {}) => <label className="account-field">{label}<input type={type} value={form[key]} required onChange={e => setForm(value => ({ ...value, [key]: e.target.value }))} {...props}/></label>;
  if (loading) return <p className="loading" role="status">Carregando conta…</p>;
  if (account) return <div className="registration-width account-page"><div className="reservation-heading"><div><p className="eyebrow">MINHA CONTA · TESTE</p><h1>Olá, {account.name}.</h1><p>{account.email}</p></div><button className="outline-action" onClick={logout}><LogOut size={16}/> Sair da conta</button></div><div className="account-actions"><Button href={next === '/inscricao' ? next : '/inscricao'}>Fazer inscrição <ArrowRight size={15}/></Button>{account.role === 'admin' && <Button outline href="/admin/reservas">Painel de reservas</Button>}</div><h2>Minhas reservas</h2><OrderList orders={orders}/></div>;
  return <div className="registration-width account-page account-grid"><div className="account-welcome"><p className="eyebrow">UM ENCONTRO PARA LEMBRAR</p><h1>Seu cadastro.<br/><em>Tudo em um só lugar.</em></h1><p>Crie uma conta de teste para reunir inscrições, acompanhar pagamentos e consultar suas reservas.</p><ul><li><CheckCircle2 size={17}/> Cadastro de participantes</li><li><CheckCircle2 size={17}/> Pagamento simulado em Pix, boleto ou cartão</li><li><CheckCircle2 size={17}/> Histórico e acompanhamento</li></ul><a href="/inscricao">Continuar como visitante <ArrowRight size={15}/></a></div><div className="account-card"><div className="account-tabs">{[['register', 'Criar cadastro'], ['login', 'Entrar']].map(([value, label]) => <button key={value} aria-pressed={tab === value} onClick={() => { setTab(value); setError(''); }}>{label}</button>)}</div><h2>{tab === 'register' ? 'Vamos começar?' : 'Bem-vinda de volta.'}</h2><p>Use somente dados fictícios. Este acesso funciona nesta aba; não envia e-mail nem cria conta real.</p><button className="text-button" onClick={() => setForm({ name: 'Visitante Exemplo', email: 'visitante@example.invalid', code: '123456', confirm: '123456' })}>Preencher exemplo · código 123456</button><form onSubmit={submit}>{tab === 'register' && field('name', 'Nome fictício', 'text', { maxLength: 100, autoComplete: 'off' })}{field('email', 'E-mail de teste', 'email', { placeholder: 'seunome@example.invalid', maxLength: 100, autoComplete: 'off' })}<small>Termine o e-mail com @example.invalid.</small>{field('code', 'Código de acesso de teste (6 dígitos)', 'password', { pattern: '[0-9]{6}', maxLength: 6, inputMode: 'numeric', autoComplete: 'off' })}{tab === 'register' && field('confirm', 'Repita o código de teste', 'password', { pattern: '[0-9]{6}', maxLength: 6, inputMode: 'numeric', autoComplete: 'off' })}<p className="signup-hint">Escolha um código fictício. Não use sua senha pessoal.</p>{error && <p role="alert" className="signup-alert">{error}</p>}<Button type="submit" disabled={busy}>{busy ? 'Processando…' : tab === 'register' ? 'Criar conta de teste' : 'Entrar na conta de teste'}</Button></form></div></div>;
}

export function ReservationsPage() {
  return <AdminAccess><Frame title="Reservas e pagamentos">{service.mode === 'demo' ? <ReservationsContent/> : <DemoOnly/>}</Frame></AdminAccess>;
}
function ReservationsContent() {
  const [account, setAccount] = useState(null), [loading, setLoading] = useState(true), [orders, setOrders] = useState([]), [accounts, setAccounts] = useState([]), [rooms, setRooms] = useState([]);
  const [tab, setTab] = useState('orders'), [search, setSearch] = useState(''), [status, setStatus] = useState(''), [method, setMethod] = useState(''), [selectedId, setSelectedId] = useState(null);
  const [error, setError] = useState(''), [notice, setNotice] = useState(''), [busy, setBusy] = useState(false);
  async function refresh() { const [list, people, inventory] = await Promise.all([service.listOrders(), service.listAccounts(), service.inventory()]); setOrders(list); setAccounts(people); setRooms(inventory); }
  useEffect(() => { let active = true; service.currentAccount().then(async user => { if (!active) return; setAccount(user); if (user?.role === 'admin') await refresh(); }).catch(err => active && setError(err.message)).finally(() => active && setLoading(false)); return () => { active = false; }; }, []);
  async function act(action, message) { setBusy(true); setError(''); setNotice(''); try { await action(); await refresh(); if (message) setNotice(message); } catch (err) { setError(err.message); } finally { setBusy(false); } }
  async function enter() { setBusy(true); setError(''); try { setAccount(await service.enterDemoAdmin()); await refresh(); } catch (err) { setError(err.message); } finally { setBusy(false); } }
  async function logout() { await service.logout(); setAccount(null); setOrders([]); }
  const selected = orders.find(x => x.id === selectedId);
  const filtered = orders.filter(order => (!status || order.status === status) && (!method || order.paymentMethod === method) && `${order.id} ${order.accommodation} ${order.participants.map(x => x.name).join(' ')}`.toLocaleLowerCase('pt-BR').includes(search.toLocaleLowerCase('pt-BR')));
  function download() { const url = URL.createObjectURL(new Blob([ordersCsv(filtered)], { type: 'text/csv;charset=utf-8;' })); const link = document.createElement('a'); link.href = url; link.download = 'reservas-demonstracao.csv'; link.click(); setTimeout(() => URL.revokeObjectURL(url), 1000); }
  if (loading) return <p className="loading" role="status">Carregando reservas…</p>;
  if (account?.role !== 'admin') return <div className="registration-width demo-admin-entry"><p className="eyebrow">ADMINISTRAÇÃO DO EVENTO · DEMONSTRAÇÃO</p><h1>Um encontro bem cuidado,<br/><em>em cada detalhe.</em></h1><p>Veja reservas, cadastros, acomodações e pagamentos simulados. O painel de teste é aberto e mostra apenas os testes feitos nesta aba.</p><Button onClick={enter} disabled={busy}>{busy ? 'Abrindo…' : 'Abrir painel demonstrativo'}<ArrowRight size={16}/></Button>{error && <p role="alert">{error}</p>}<small>Acesso de demonstração, sem dados reais.</small></div>;
  return <div className="registration-width reservations-page"><div className="reservation-heading"><div><p className="eyebrow">ORGANIZAÇÃO · RECEPÇÃO DO SUPREMO TIME</p><h1>Reservas e pagamentos.</h1><p>Sábado, 23 de janeiro de 2027 · SESC Copacabana, a confirmar</p></div><button className="outline-action" onClick={logout}><LogOut size={16}/> Sair do teste</button></div><p className="dashboard-demo-note">Dados desta aba. Valores, estoque, pagamentos e presenças são fictícios.</p>
    <div className="reservation-stats">{[[Ticket, 'Reservas', orders.length, `${orders.filter(x => x.status === 'pending').length} pendentes`], [Users, 'Participantes confirmados', orders.filter(x => x.status === 'confirmed').reduce((n, x) => n + x.participantCount, 0), `${orders.reduce((n, x) => n + x.participants.filter(p => p.checkedIn).length, 0)} presenças`], [Wallet, 'Recebido no teste', currency(orders.filter(x => x.status === 'confirmed').reduce((n, x) => n + x.totalCents, 0)), 'Pagamentos aprovados'], [BedDouble, 'Hospedagens confirmadas', orders.filter(x => x.status === 'confirmed' && x.accommodationId !== 'evento').length, 'Quartos ou vagas de teste']].map(([Icon, label, value, detail]) => <article key={label}><Icon size={21}/><span>{label}</span><strong>{value}</strong><small>{detail}</small></article>)}</div>
    <div className="reservation-toolbar"><nav aria-label="Gestão do evento">{[['orders', 'Reservas'], ['accounts', 'Cadastros'], ['rooms', 'Acomodações']].map(([value, label]) => <button key={value} aria-pressed={tab === value} onClick={() => setTab(value)}>{label}</button>)}</nav><div><button className="outline-action" disabled={busy} onClick={() => act(() => service.loadExamples(), 'Exemplos disponíveis. Os pedidos existentes foram preservados.')}>Carregar exemplos</button><Button href="/inscricao">Nova reserva <ArrowRight size={14}/></Button></div></div>
    {error && <p className="signup-alert" role="alert">{error}</p>}{notice && <p className="dashboard-notice" role="status">{notice}</p>}
    {tab === 'orders' && <><div className="reservation-filters"><label><Search size={16}/><input aria-label="Buscar reserva ou participante" placeholder="Código ou participante" value={search} onChange={e => setSearch(e.target.value)}/></label><label>Status da reserva<select value={status} onChange={e => setStatus(e.target.value)}><option value="">Todos os status</option>{Object.entries(statusNames).map(([id, name]) => <option key={id} value={id}>{name}</option>)}</select></label><label>Pagamento<select value={method} onChange={e => setMethod(e.target.value)}><option value="">Todas as formas</option>{Object.entries(paymentNames).map(([id, name]) => <option key={id} value={id}>{name}</option>)}</select></label><button className="outline-action" onClick={download} disabled={!filtered.length}><Download size={15}/> Exportar CSV</button></div><div className="reservation-table-wrap"><table className="reservation-table"><caption>{filtered.length} reserva(s) de teste</caption><thead><tr><th>Reserva / participante</th><th>Acomodação</th><th>Pagamento</th><th>Total</th><th>Status</th><th><span className="sr-only">Ações</span></th></tr></thead><tbody>{filtered.map(order => <tr key={order.id}><td><strong>{order.id}</strong><span>{order.participants[0]?.name}</span><small>{date(order.createdAt)} · {order.participantCount} pessoa(s)</small></td><td>{order.accommodation}<small>{order.lot}</small></td><td>{order.paymentLabel}<small>{paymentStatusNames[order.paymentStatus]}</small></td><td>{currency(order.totalCents)}</td><td><span className={`reservation-badge status-${order.status}`}>{statusNames[order.status]}</span></td><td><button className="outline-action" onClick={() => setSelectedId(order.id)}>Detalhes</button></td></tr>)}</tbody></table>{!filtered.length && <div className="reservation-empty"><Ticket size={30}/><h2>{orders.length ? 'Nenhuma reserva neste filtro.' : 'Tudo pronto para a primeira reserva.'}</h2><p>{orders.length ? 'Altere os filtros para encontrar um pedido.' : 'Faça uma inscrição pelo site ou carregue exemplos para explorar o painel.'}</p></div>}</div></>}
    {tab === 'accounts' && <section className="account-directory"><div className="reservation-heading"><div><h2>Cadastros de teste</h2><p>Contas criadas nesta aba e suas reservas vinculadas.</p></div><Button href="/conta?novo=1">Novo cadastro</Button></div>{accounts.length ? accounts.map(person => <article key={person.id}><Users size={24}/><div><h3>{person.name}</h3><p>{person.email}</p><small>Criado em {date(person.createdAt)}</small></div><b>{person.orders} reserva(s)</b></article>) : <p className="reservation-empty">Nenhuma conta cadastrada. Use “Criar cadastro” na área Minha conta.</p>}</section>}
    {tab === 'rooms' && <section className="inventory-section"><h2>Acomodações e disponibilidade</h2><p>Estoque ilustrativo para testar: pedidos pendentes separam disponibilidade; cancelamentos, expirações e estornos a liberam.</p><div className="inventory-grid">{rooms.map(room => <article key={room.id}><BedDouble size={24}/><h3>{room.label}</h3><p>{room.capacity} {room.unit} no total</p><dl><div><dt>Disponíveis</dt><dd>{room.available}</dd></div><div><dt>Pendentes</dt><dd>{room.held}</dd></div><div><dt>Confirmados</dt><dd>{room.occupied}</dd></div></dl></article>)}</div></section>}
    {selected && <ReservationDetail key={selected.id} order={selected} busy={busy} error={error} onClose={() => { setSelectedId(null); setError(''); }} onAction={act}/>}
  </div>;
}

function ReservationDetail({ order, busy, error, onClose, onAction }) {
  useEffect(() => { const previous = document.activeElement; const dialog = document.getElementById('reservation-detail'); dialog?.focus(); const keydown = e => { if (e.key === 'Escape' && !busy) onClose(); if (e.key === 'Tab') { const nodes = [...dialog.querySelectorAll('button:not(:disabled),a[href],input:not(:disabled)')]; const first = nodes[0], last = nodes.at(-1); if (e.shiftKey && (document.activeElement === first || document.activeElement === dialog)) { e.preventDefault(); last?.focus(); } else if (!e.shiftKey && document.activeElement === last) { e.preventDefault(); first?.focus(); } } }; document.addEventListener('keydown', keydown); return () => { document.removeEventListener('keydown', keydown); previous?.focus(); }; }, [busy, onClose]);
  return <div className="reservation-overlay"><section className="reservation-detail" id="reservation-detail" tabIndex={-1} role="dialog" aria-modal="true" aria-labelledby="reservation-detail-title"><div className="reservation-heading"><div><p className="eyebrow">RESERVA DE TESTE</p><h2 id="reservation-detail-title">{order.id}</h2><p>{order.source} · {date(order.createdAt)}</p></div><button className="outline-action" disabled={busy} onClick={onClose}>Fechar</button></div><div className="reservation-detail-facts"><span>{order.accommodation}</span><span>{order.paymentLabel} {order.paymentMethod === 'card' && `· ${order.installments}x`}</span><strong>{currency(order.totalCents)}</strong><span className={`reservation-badge status-${order.status}`}>{statusNames[order.status]}</span></div><h3>Participantes e presença</h3><div className="detail-participants">{order.participants.map(person => <article key={person.id}><div><strong>{person.name}</strong><small>{person.category} · Camisa {person.shirt}</small><small>{person.bethel || 'Vínculo não informado'}</small></div><label><input type="checkbox" checked={person.checkedIn} disabled={busy || order.status !== 'confirmed'} onChange={e => onAction(() => service.setCheckIn(order.id, person.id, e.target.checked))}/> Presença</label></article>)}</div><p className="signup-hint">A presença fica disponível após a aprovação do pagamento de teste.</p>{error && <p role="alert" className="signup-alert">{error}</p>}<div className="reservation-actions">{(order.status === 'pending' ? [['confirmed', 'Aprovar pagamento'], ['declined', 'Recusar pagamento'], ['expired', 'Simular expiração'], ['cancelled', 'Cancelar reserva']] : order.status === 'confirmed' ? [['refunded', 'Simular estorno']] : []).map(([status, label]) => <button key={status} className="outline-action" disabled={busy} onClick={() => onAction(() => service.setDemoStatus(order.id, status))}>{label}</button>)}</div><p className="dashboard-demo-note">Todas as ações acima alteram somente esta simulação.</p><PaymentHistory order={order}/><a className="detail-tracking" href={`/acompanhamento?codigo=${order.id}`}>Ver como participante <ArrowRight size={15}/></a></section></div>;
}

