import { useEffect } from 'react';
import { CalendarDays, MapPin, Clock3, ArrowRight, Users, Ticket, TicketCheck, CreditCard } from 'lucide-react';
import Header from '../components/Header';
import Sponsors from '../components/Sponsors';
import { Brand, Button, Label } from '../components/Shared';
import { useContent } from '../hooks/useContent';
import { first } from '../data/defaults';
import { demoCatalog } from './catalog';
import { previewSponsors } from './sponsors';
import '../styles/event-page.css';

export default function EventPage() {
  const content = useContent(), site = first(content, 'site_settings'), contact = first(content, 'contact_info');
  useEffect(() => { document.title = 'Recepção do Supremo Time — Filhas de Jó RJ'; }, []);
  useEffect(() => {
    const targetId = window.location.hash.slice(1);
    if (!targetId) return;
    let active = true;
    document.fonts.ready.then(() => {
      if (active) document.getElementById(targetId)?.scrollIntoView({ behavior: 'instant', block: 'start' });
    });
    return () => { active = false; };
  }, []);
  return <div className="event-public"><a className="skip-link" href="#conteudo">Pular para o conteúdo</a><Header site={site} sections={content.sections} contact={contact} registration={first(content, 'registration_settings')} onModal={() => { location.href = '/#contato'; }}/><main id="conteudo">
    <section className="reception-hero" id="inicio"><img className="reception-image" src="/assets/hero-rio.webp" alt="Ilustração das Filhas de Jó diante da paisagem do Rio de Janeiro" fetchPriority="high"/><div className="reception-shade"/><div className="wrap reception-copy"><a className="event-breadcrumb" href="/">Filhas de Jó RJ <span>/</span> Nosso evento</a><Label>RIO DE JANEIRO · 23 DE JANEIRO DE 2027</Label><h1>Recepção do<br/><span>Supremo Time</span></h1><p>Um dia de aprendizado, convivência e celebração com a Diretoria Executiva Internacional das Filhas de Jó.</p><div className="reception-actions"><Button href="/inscricao">Fazer minha inscrição <ArrowRight size={17}/></Button><Button outline href="/acompanhamento"><TicketCheck size={17}/>Acompanhar inscrição</Button></div><a className="reception-program-link" href="#programacao">Conhecer a programação <ArrowRight size={14}/></a></div><svg className="hero-cut" viewBox="0 0 1440 100" preserveAspectRatio="none" aria-hidden="true"><path d="M0 5 L130 78 L430 49 L740 93 L1070 67 L1440 16 L1440 100 L0 100Z" fill="#F8F6F3"/><path d="M0 5 L130 78 L430 49 L740 93 L1070 67 L1440 16" fill="none" stroke="#D4AF37" strokeWidth="3"/></svg></section>
    <section className="reception-facts wrap" aria-label="Informações do evento">{[[CalendarDays, '23 de janeiro', 'Sábado · 2027'], [Clock3, 'A partir das 8h', 'Programação em um único dia'], [MapPin, 'SESC Copacabana', 'Local solicitado · a confirmar']].map(([Icon, title, detail]) => <div key={title}><Icon size={27} strokeWidth={1.3}/><p><strong>{title}</strong><span>{detail}</span></p></div>)}</section>
    <section className="reception-about wrap"><div className="reception-about-picture"><img src="/assets/amizade.webp" alt="Ilustração sobre os laços de amizade das Filhas de Jó" loading="lazy"/></div><div><Label>NOSSO ENCONTRO</Label><h2>O Rio recebe.<br/>A irmandade se encontra.</h2><p>No dia 23 de janeiro, recebemos o Supremo Time para compartilhar experiências, aprender e fortalecer os laços da nossa organização.</p><p>A programação reúne café, abertura, palestra, almoço e treinamentos. Ao fim do dia, um coquetel homenageia nossas visitantes.</p><a className="reception-text-link" href="#programacao">Confira os horários <ArrowRight size={15}/></a></div><aside><img src="/assets/logo-filhas-de-jo-rj.png" alt="Filhas de Jó RJ"/><span>FILHAS DE JÓ INTERNACIONAL</span><strong>Rio de Janeiro</strong><p>Recepção do Supremo Time<br/>23 de janeiro de 2027</p></aside></section>
    <section className="reception-program" id="programacao"><div className="wrap reception-program-inner"><div><Label>PROGRAMAÇÃO · SÁBADO, 23/01</Label><h2>Um dia para<br/>estarmos juntas.</h2><p>Da recepção ao coquetel, confira cada momento do encontro.</p><Button href="/inscricao">Fazer minha inscrição <ArrowRight size={16}/></Button></div><ol>{demoCatalog.schedule.map(item => <li key={item.time}><time dateTime={`2027-01-23T${item.time}`}>{item.time.replace(':', 'h')}</time><h3>{item.title}</h3></li>)}</ol></div></section>
    <section className="reception-signup wrap" id="inscricoes"><div className="reception-section-heading"><div><Label>INSCRIÇÕES</Label><h2>Sua presença começa aqui.</h2></div><p>Organize a participação da sua família ou do seu grupo em poucos passos.</p></div><div className="reception-steps">{[[Ticket, '01', 'Escolha sua participação', 'Consulte as opções de inscrição e selecione a categoria dos participantes.'], [Users, '02', 'Cadastre quem vem', 'Preencha os dados de cada pessoa e confira as informações do seu grupo.'], [CreditCard, '03', 'Revise e acompanhe', 'Veja o resumo do pedido, a etapa de pagamento e o acompanhamento da inscrição.']].map(([Icon, number, title, text]) => <article key={number}><div><Icon size={26} strokeWidth={1.3}/><span>{number}</span></div><h3>{title}</h3><p>{text}</p></article>)}</div><div className="reception-signup-actions"><Button href="/inscricao">Começar minha inscrição <ArrowRight size={17}/></Button><a href="/conta">Minha conta <ArrowRight size={14}/></a></div></section>
    <section className="reception-questions wrap"><div><Label>INFORMAÇÕES IMPORTANTES</Label><h2>Antes do encontro.</h2></div><div>{[['Quando acontece?', 'A recepção acontece somente no sábado, 23 de janeiro de 2027, a partir das 8h. O encerramento das atividades será às 17h e o coquetel em homenagem ao Supremo Time começa às 18h.'], ['Onde será o evento?', 'O local solicitado é o SESC Copacabana, no Rio de Janeiro. A confirmação da reserva será informada pela organização.'], ['Como faço a inscrição do meu grupo?', 'Acesse a página de inscrição, escolha sua participação e preencha os dados de cada pessoa. Você pode usar o mesmo endereço para os participantes do grupo.'], ['Como acompanho meu pedido?', 'Use o código gerado ao concluir o cadastro na página de acompanhamento. As condições de participação e pagamento são apresentadas durante a inscrição.']].map(([question, answer]) => <details key={question}><summary>{question}</summary><p>{answer}</p></details>)}</div></section>
    <Sponsors items={previewSponsors(content.sponsors)} onContact={() => { location.href = '/#contato'; }}/>
    <section className="reception-contact"><div className="wrap"><div><Label>FALE COM A ORGANIZAÇÃO</Label><h2>Podemos ajudar você.</h2><p>Entre em contato para esclarecer suas dúvidas sobre o encontro.</p></div><Button href="/#contato">Falar com a equipe <ArrowRight size={16}/></Button></div></section>
  </main><footer className="footer reception-footer"><div className="wrap footer-main"><Brand site={site}/><nav aria-label="Navegação do rodapé"><a href="/">Site institucional</a><a href="#programacao">Programação</a><a href="/inscricao">Inscrições</a><a href="/acompanhamento">Acompanhar pedido</a></nav></div></footer></div>;
}
