const {chromium}=require('C:/Users/User/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const fs=require('node:fs');
(async()=>{
const {defaults}=await import('../src/data/defaults.js');const content=structuredClone(defaults);Object.values(content).forEach(rows=>rows.forEach(row=>row.updated_at='2026-09-14T00:00:00Z'));
const browser=await chromium.launch({headless:true,channel:'msedge'});const page=await browser.newPage({viewport:{width:1440,height:1000},reducedMotion:'reduce'});const errors=[];page.on('pageerror',e=>errors.push(e.message));
const user={id:'00000000-0000-0000-0000-000000000001',email:'admin-ui-test@example.invalid',aud:'authenticated',role:'authenticated'};
const token=['eyJhbGciOiJIUzI1NiJ9',Buffer.from(JSON.stringify({sub:user.id,exp:Math.floor(Date.now()/1000)+3600,role:'authenticated'})).toString('base64url'),'mock-signature'].join('.');
await page.addInitScript(({user,token})=>localStorage.setItem('sb-godvzqqmsrkyvlflmadd-auth-token',JSON.stringify({access_token:token,refresh_token:'mock-refresh',expires_at:Math.floor(Date.now()/1000)+3600,expires_in:3600,token_type:'bearer',user})),{user,token});
await page.route('https://godvzqqmsrkyvlflmadd.supabase.co/**',async route=>{const req=route.request(),url=new URL(req.url()),name=url.pathname.split('/').pop();let body;if(url.pathname.includes('/auth/'))body={user};else if(name==='admin_profiles')body={id:user.id,active:true};else if(name==='swap_sections'){const input=req.postDataJSON();const a=content.sections.find(s=>s.id===input.p_first),b=content.sections.find(s=>s.id===input.p_second);[a.sort_order,b.sort_order]=[b.sort_order,a.sort_order];body=null;}else if(content[name]){const rows=content[name];if(req.method()==='PATCH'){const id=url.searchParams.get('id')?.slice(3);const row=rows.find(r=>r.id===id);Object.assign(row,req.postDataJSON());body=[row];}else if(req.method()==='POST'){const row={...req.postDataJSON(),id:'new-test-row',updated_at:'2026-09-14T00:00:00Z'};rows.push(row);body=[row];}else if(req.method()==='DELETE'){const id=url.searchParams.get('id')?.slice(3);const idx=rows.findIndex(r=>r.id===id);body=rows.splice(idx,1);}else body=[...rows].sort((a,b)=>a.sort_order-b.sort_order);}else body=[];await route.fulfill({status:200,contentType:'application/json',body:JSON.stringify(body)});});
await page.goto('http://127.0.0.1:5173/admin',{waitUntil:'networkidle'});await page.getByRole('heading',{name:'Visão geral',exact:true}).waitFor();await page.screenshot({path:'docs/qa/admin-dashboard.png',fullPage:true});
await page.getByRole('navigation',{name:'Áreas de administração'}).getByRole('button',{name:'Evento',exact:true}).click();await page.getByRole('button',{name:'Editar conteúdo',exact:true}).click();await page.getByLabel('Nome provisório do evento',{exact:true}).fill('Encontro de teste');await page.getByRole('button',{name:'Salvar alterações',exact:true}).click();await page.getByRole('heading',{name:'Encontro de teste',exact:true}).waitFor();
await page.getByRole('navigation',{name:'Áreas de administração'}).getByRole('button',{name:'Perguntas frequentes',exact:true}).click();await page.getByRole('button',{name:'Adicionar item',exact:true}).click();await page.getByLabel('Pergunta',{exact:true}).fill('Pergunta de teste');await page.getByLabel('Resposta',{exact:true}).fill('Resposta para verificar edição.');await page.getByRole('button',{name:'Salvar alterações',exact:true}).click();await page.getByRole('heading',{name:'Pergunta de teste',exact:true}).waitFor();const article=page.locator('article').filter({hasText:'Pergunta de teste'});await article.getByRole('button',{name:'Excluir item',exact:true}).click();await page.getByRole('dialog').getByRole('button',{name:'Excluir item',exact:true}).click();await page.getByRole('heading',{name:'Pergunta de teste',exact:true}).waitFor({state:'detached'});
await page.getByRole('button',{name:'Seções do site',exact:true}).click();await page.getByRole('button',{name:'Descer Quem Somos',exact:true}).click();if(content.sections.find(s=>s.slug==='sobre').sort_order!==2)throw Error('Order did not save');
console.log(JSON.stringify({errors,result:'PASS: mocked-session admin dashboard, event save, FAQ create/delete, section reorder. Live authorization tested separately via rollback SQL.'}));await browser.close();if(errors.length)process.exit(1);
})().catch(e=>{console.error(e);process.exit(1)});
