const f=(key,label,type='text',options)=>({key,label,type,options});
export const editors={
site_settings:{label:'Identidade',single:true,folder:'branding',fields:[f('name','Nome do site'),f('tagline','Assinatura da marca'),f('logo','Logo oficial','image'),f('primary_color','Roxo principal','color'),f('gold_color','Dourado','color'),f('dark_color','Fundo escuro','color')]},
hero_content:{label:'Banner principal',single:true,folder:'hero',fields:[f('eyebrow','Texto acima do título'),f('title','Título'),f('subtitle','Subtítulo','textarea'),f('description','Descrição','textarea'),f('image','Imagem de fundo','image'),f('primary_text','Botão principal'),f('primary_url','Destino do botão'),f('secondary_text','Botão do vídeo'),f('video_url','Link do vídeo'),f('show_secondary','Exibir botão do vídeo','checkbox'),f('quote','Frase decorativa','textarea')]},
about_content:{label:'Quem somos',single:true,folder:'about',fields:[f('title','Título','textarea'),f('text','Texto','textarea'),f('image','Imagem','image'),f('button_text','Texto do botão')]},
history_content:{label:'Nossa história',single:true,folder:'history',fields:[f('title','Título','textarea'),f('text','Texto','textarea'),f('image','Foto histórica','image'),f('timeline','Linha do tempo','timeline')]},
event_info:{label:'Evento',single:true,folder:'hero',fields:[f('name','Nome provisório do evento'),f('slogan','Chamada','textarea'),f('description','Descrição','textarea'),f('date','Data','date'),f('time','Horário','time'),f('venue','Local'),f('address','Endereço'),f('city','Cidade'),f('map_url','Link do mapa'),f('capacity','Número de vagas','number'),f('status','Status','select',['Em preparação','Confirmado','Adiado','Encerrado']),f('image','Banner do evento','image'),f('quote','Frase decorativa','textarea')]},
values:{label:'Valores',fields:[f('title','Título'),f('description','Descrição','textarea'),f('icon','Ícone','select',['Crown','Users','Heart','HandHeart','Landmark','Star'])]},
schedule_items:{label:'Programação',fields:[f('date','Data','date'),f('time','Horário','time'),f('title','Título'),f('description','Descrição','textarea'),f('location','Local'),f('responsible','Responsável')]},
guests:{label:'Convidados',folder:'guests',fields:[f('name','Nome'),f('role','Cargo'),f('description','Descrição','textarea'),f('photo','Foto','image'),f('instagram','Link do Instagram')]},
gallery:{label:'Galeria',folder:'gallery',fields:[f('image','Imagem','image'),f('caption','Legenda'),f('illustrative','Imagem ilustrativa','checkbox')]},
sponsors:{label:'Apoiadores',folder:'sponsors',fields:[f('name','Nome'),f('logo','Logo','image'),f('url','Link'),f('category','Categoria','select',['Realização','Apoio Institucional','Patrocínio','Parceiros']),f('description','Descrição','textarea')]},
faq:{label:'Perguntas frequentes',fields:[f('question','Pergunta'),f('answer','Resposta','textarea')]},
contact_info:{label:'Contato',single:true,folder:'hero',fields:[f('title','Título'),f('description','Descrição'),f('email','E-mail público','email'),f('whatsapp','WhatsApp com código do país'),f('instagram','Link do Instagram'),f('youtube','Link do YouTube'),f('facebook','Link do Facebook'),f('tiktok','Link do TikTok'),f('address','Endereço','textarea'),f('image','Banner','image'),f('quote','Frase decorativa','textarea')]},
social_links:{label:'Outros links',fields:[f('name','Nome'),f('url','Link')]},
registration_settings:{label:'Inscrições',single:true,fields:[f('open','Inscrições abertas','checkbox'),f('button_text','Texto do botão'),f('external_url','Link externo de inscrição'),f('price','Valor (R$)','number'),f('notes','Observações','textarea'),f('payment_methods','Formas de pagamento','textarea')]},
registration_lots:{label:'Lotes de ingresso',fields:[f('name','Nome do lote'),f('price','Valor (R$)','number'),f('start_date','Início','date'),f('end_date','Fim','date'),f('capacity','Vagas','number'),f('notes','Observações','textarea')]}
};
